### ISSUE TITLE
TK# 01

### ISSUE THREAD

**Issue by gonzaloijuarez** [gonzaloijuarez/Proyecto-FullStack#12]
Diseño de sitio

**Comment by AliciaRomanzini** [comment]
![Image](https://user-images.githubusercontent.com/106454850/201488133-5c260ddd-5d6d-4c06-a3fd-f1179ccaeb85.png)



![Image](https://user-images.githubusercontent.com/106454850/201488140-b710bf50-1595-47ec-a495-2f7ceb1bcd84.png)

**Comment by AliciaRomanzini** [comment]
Este es el logo y el diseño para aplicar al sitio que realicé
